import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, test } from 'vitest'

const appSource = readFileSync(fileURLToPath(new URL('./App.tsx', import.meta.url)), 'utf8')
const css = readFileSync(fileURLToPath(new URL('./index.css', import.meta.url)), 'utf8')

describe('link health maintenance contract', () => {
  test('shows stored problem links in edit mode with safe maintenance actions', () => {
    expect(appSource).toContain('checkLinks')
    expect(appSource).toContain('getStoredLinkCheckResults')
    expect(appSource).toContain('confirmLinkCheckResult')
    expect(appSource).toContain('const [isCheckingLinks, setIsCheckingLinks]')
    expect(appSource).toContain('type CheckFilter')
    expect(appSource).toContain('const [checkFilter, setCheckFilter]')
    expect(appSource).toContain('const [linkCheckProgress, setLinkCheckProgress]')
    expect(appSource).toContain('const storedLinkCheckResults = useMemo')
    expect(appSource).toContain('const visibleLinkCheckResults =')
    expect(appSource).toContain('const filteredLinkCheckResults = useMemo')
    expect(appSource).toContain('const problemLinkChecks = useMemo')
    expect(appSource).toContain("check.status === 'broken'")
    expect(appSource).toContain("item.status === 'broken'")
    expect(appSource).toContain('无法确认')
    expect(appSource).toContain('const problemLinkStatusById = useMemo')
    expect(appSource).toContain('async function runLinkCheck()')
    expect(appSource).toContain('applyLinkCheckResults')
    expect(appSource).toContain('checkLinks(')
    expect(appSource).toContain('function findLinkForCheck(')
    expect(appSource).toContain('function confirmHealthyLink(')
    expect(appSource).toContain('检测网址')
    expect(appSource).toContain('isCheckingLinks')
    expect(appSource).toContain('className="notice-panel maintenance-panel"')
    expect(appSource).toContain('检测结果筛选')
    expect(appSource).toContain('className="check-progress"')
    expect(appSource).toContain('className="check-result-list"')
    expect(appSource).toContain('className={`check-result is-${item.status}`}')
    expect(appSource).toContain('locateLink(item.groupId, item.linkId)')
    expect(appSource).toContain('deleteLink(item.groupId, item.linkId)')
    expect(appSource).toContain('confirmHealthyLink(item.linkId)')
    expect(appSource).toContain('problemLinkStatusById.get(link.id)')
    expect(appSource).toContain('has-link-check')
    expect(appSource).toContain('health-badge')
  })

  test('styles the link health panel and highlighted cards', () => {
    expect(css).toContain('.maintenance-panel')
    expect(css).toContain('.check-progress')
    expect(css).toContain('.check-result-list')
    expect(css).toContain('.check-result')
    expect(css).toContain('.check-result.is-broken')
    expect(css).toContain('.check-result.is-limited')
    expect(css).toContain('.link-card-shell.has-link-check.is-broken .link-card')
    expect(css).toContain('.link-card-shell.has-link-check.is-limited .link-card')
    expect(css).toContain('.health-badge')
  })
})
